---
image: python:bookworm

stages:
  - setup
  - test
  - deploy

.base:
  before_script:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - python3 setup.py install

install:
  stage: setup
  extends: .base
  script:
    - /bin/true

functional_tests:
  stage: test
  extends: .base
  script:
    - pytest --cov-report=term-missing --cov=onionbalance test/functional/

unit_tests:
  stage: test
  extends: .base
  script:
    - pytest --cov-report=term-missing --cov=onionbalance --ignore=test/functional/

static_tests:
  stage: test
  extends: .base
  script:
    - pylint onionbalance --disable=R,C,W

style_tests:
  stage: test
  extends: .base
  script:
    - flake8 onionbalance

docs:
  stage: deploy
  extends: .base
  script:
    - sphinx-build -W -b html -d ./docs/_build ./docs ./docs/_build/html

pages:
  stage: deploy
  script:
    - cp -a docs/_build/html public
