# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - rm -rf vendors/onion-mkdocs
      - mkdir -p vendors/
      - git clone https://gitlab.torproject.org/tpo/web/onion-mkdocs.git vendors/onion-mkdocs
      - vendors/onion-mkdocs/scripts/onion-mkdocs-provision-build
      - vendors/onion-mkdocs/scripts/onion-mkdocs-build
      - scripts/docs-preserve-historic-urls
      - PIPENV_PIPFILE=vendors/onion-mkdocs/Pipfile pipenv requirements

mkdocs:
  configuration: mkdocs.yml
